---
- hosts: all
  become: true
  tasks:
    - name: Install apache httpd
      yum:
        name: apache2
        state: present
        update_cache: yes
    - name: restart the apache server
      service:
        name: httpd
        state: restarted
    - name: Copy file with owner and permissions
      copy:
        src: index.html
        dest: /var/www/html
        owner: root
        group: root
        mode: '0644'
